name: Production Build Linux

on:
  push:
    branches:
      - "master"
    paths:
      - "pkg/**"
      - ".github/workflows/**"
      - "go.mod"
      - "main.go"
  pull_request:
    paths:
      - "pkg/**"
      - ".github/workflows/**"
      - "go.mod"
      - "main.go"

jobs:
  production-build-linux:
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-18.04", "ubuntu-20.04", "ubuntu-latest"]
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Setup the Golang environment with version 1.13.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x

      - name: Run a Go build
        run: go build -o bin/main main.go
