name: Production Build Windows

on:
  push:
    branches:
      - "master"
    paths:
      - "pkg/**"
      - ".github/workflows/**"
      - "go.mod"
      - "main.go"
  pull_request:
    paths:
      - "pkg/**"
      - ".github/workflows/**"
      - "go.mod"
      - "main.go"

jobs:
  production-build-windows:
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP CI]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2016", "windows-2019", "windows-2022", "windows-latest"]
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Setup the Golang environment with version 1.13.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x

      - name: Run a Go build
        run: go build -o bin/main.exe main.go
